{{- if and (not .Values.existingSecrets.database) .Values.database.upstreamDb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero.fullname" . }}-database
  labels:
    {{- include "zero.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZERO_UPSTREAM_DB: {{ .Values.database.upstreamDb | quote }}
  {{- if .Values.database.cvrDb }}
  ZERO_CVR_DB: {{ .Values.database.cvrDb | quote }}
  {{- end }}
  {{- if .Values.database.changeDb }}
  ZERO_CHANGE_DB: {{ .Values.database.changeDb | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.existingSecrets.aws) (or .Values.litestream.aws.accessKeyId .Values.litestream.aws.secretAccessKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero.fullname" . }}-aws
  labels:
    {{- include "zero.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.litestream.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.litestream.aws.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.litestream.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.litestream.aws.secretAccessKey | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.existingSecrets.admin) .Values.adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero.fullname" . }}-admin
  labels:
    {{- include "zero.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZERO_ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
{{- end }}
{{- if and (not .Values.existingSecrets.auth) .Values.zero.authSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero.fullname" . }}-auth
  labels:
    {{- include "zero.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZERO_AUTH_SECRET: {{ .Values.zero.authSecret | quote }}
{{- end }}
